# Generated by Django 4.0 on 2022-10-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.log')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
